// GERADO por scripts/merge-laminas-en.py — NÃO editar à mão.
// dor_hook em inglês por UC (camada de tradução do site; ver ADR-0005).
export const DOR_HOOK_EN: Record<string, string> = {
 "UC-001": "My sales pipeline lives in a spreadsheet and in my head — and a stalled proposal goes cold without anyone noticing.",
 "UC-002": "Too many leads come in and I can't respond in time — the good ones go cold waiting.",
 "UC-003": "Once I close, the contract turns into a folder lost in Drive — and the renewal always catches me off guard.",
 "UC-004": "I closed the sale and now a step in onboarding always slips through — the new customer hears nothing and starts to doubt.",
 "UC-005": "I only find out a customer is unhappy once they've already asked to cancel.",
 "UC-006": "WhatsApp support swallows my team, and after hours the customer is left hanging.",
 "UC-007": "The due date passes and nobody notices in time.",
 "UC-008": "Purchasing here is a game of telephone: I overpay and I can't say who approved what.",
 "UC-009": "Reimbursement here is a photo of a receipt over WhatsApp and good faith — if an audit hits, I can't prove a thing.",
 "UC-010": "I spend hours a week putting together status because the client has no way to see for themselves where their project stands.",
 "UC-011": "I open a role and drown in résumés — and I end up giving almost nobody a reply.",
 "UC-012": "On the way in, something's always missing; on the way out, the ex-employee's access stays live for weeks.",
 "UC-013": "My techs are out in the field and the information vanishes — the customer calls \"when's he coming?\" and nobody knows.",
 "UC-014": "My inventory lives in a spreadsheet that never adds up — an item runs out and I only find out when I go to use it.",
 "UC-015": "My records are a dumpster fire: the same customer shows up three times and I send the same thing twice.",
 "UC-016": "To learn a simple number about my business, I depend on someone building a spreadsheet — and by the time it arrives, it's already changed.",
 "UC-017": "My vendors' certificates expire without anyone seeing it, and sometimes I sign with one who has a compliance issue.",
 "UC-018": "My internal policies turn into a PDF nobody signs — and I have no way to prove who accepted what.",
 "UC-019": "My metrics only get attention once the problem has already grown — and I still depend on remembering to act.",
 "UC-020": "I lose contacts that would ripen over months because I don't have the bandwidth to keep up with each one over time.",
 "UC-021": "I get big lists to clean up and it's all by hand; if it stalls midway, someone starts over from scratch.",
 "UC-022": "I send a proposal and it dies in silence — not because the customer said no, but because nobody sent the second touch.",
 "UC-023": "The renewal catches me off guard and, in the rush not to lose the customer, I end up giving away too much of a discount.",
 "UC-024": "Every month I match the bank statement against my system by hand, line by line — it takes hours, and one slip is money.",
 "UC-025": "A customer doesn't tell you they're leaving — they just go quiet, and I only notice once they're gone.",
 "UC-026": "My month-end close lives in a spreadsheet and in people's heads — and one forgotten step turns into a penalty.",
 "UC-027": "My customers ask for everything over WhatsApp — booking, rescheduling, confirming — and one person answers that all day long.",
 "UC-028": "My customers book by phone and WhatsApp all day, and outside business hours nobody can book at all.",
 "UC-029": "Quote requests come in piecemeal over WhatsApp, e-mail and Instagram, and there's always a missing detail.",
 "UC-030": "Customers keep calling to ask where their order is, and my team repeats the same answer all day long.",
 "UC-031": "My customer asks me for the same duplicate copy and the same document over and over, and I'm forever resending it by hand.",
 "UC-032": "I send a satisfaction survey, see the low s, and do nothing in time — the unhappy customer just disappears.",
 "UC-033": "I send order confirmations and payment-received notices by hand, one by one, and when I forget the customer calls worried.",
 "UC-034": "A lead that comes in through the site turns into a loose note and goes cold before anyone talks to them.",
 "UC-035": "The front desk lives on the phone confirming and rescheduling, the calendar has no-show gaps, and patient recalls slip through the cracks.",
 "UC-036": "A missed deadline isn't a delay: it's malpractice liability — and today it lives in someone's head.",
 "UC-037": "Every month it's the same hunt for documents from dozens of clients, and the filing deadline hangs by a thread.",
 "UC-038": "The lead comes in over WhatsApp, disappears mid-funnel, and the showing and the inspection turn into a scheduling mess.",
 "UC-039": "Client sign-off stalls the project, and at month-end nobody knows what's ready to bill.",
 "UC-040": "Enrolling a student is easy; the hard part is the tuition that goes late and the student who vanishes mid-course.",
 "UC-041": "Every credit application is a pile of documents, a by-hand analysis, and a decision that can't go wrong.",
 "UC-042": "After the sale comes the flood: exchanges, returns, and customers asking for order status on WhatsApp all day.",
 "UC-043": "Contract signed — now what? Build the roster, dispatch the crew, and prove the service was done, every month, by hand.",
 "UC-044": "Ten days to the event and registration, check-in, and reminders are still scattered across a spreadsheet.",
 "UC-045": "A resident's request on WhatsApp, an overdue payment, and nobody with a place to keep track of their own building.",
 "UC-046": "The member stopped coming two weeks ago and you only notice when they cancel the plan.",
 "UC-047": "The customer calls constantly to check on the repair, and the estimate sits waiting for a \"go ahead.\"",
 "UC-048": "Calling employees in for exams, tracking who's done them and when each occupational-health certificate expires — all in a spreadsheet, with a legal deadline ticking.",
 "UC-049": "I do the finance for dozens of companies a different way for each one, and at month-end it turns into a race against error.",
 "UC-050": "I'm the receptionist for several clinics at once, and every one of their WhatsApps rings on me all day.",
 "UC-051": "I handle support for several companies and the volume outgrows my team — but a bot on its own loses the customer at the hard moment.",
 "UC-052": "My consultancy became a repeatable recipe, but for every new client I still build everything from scratch.",
 "UC-053": "I only find out my client's numbers slipped when they call me worried — always too late.",
 "UC-054": "I manage a portfolio of companies, but I can only see each one separately — never the whole on a single screen.",
 "UC-055": "I wanted to start with a ready-made operation and just tune it to my business, without building everything from scratch.",
 "UC-056": "I know my niche inside out and I serve clients one by one by hand, but I can't turn that expertise into something that sells on its own.",
 "UC-057": "My methodology works, but it stays trapped in PDFs and hourly consulting — it never became a product that scales.",
 "UC-058": "I run the same operation for every client by selling my hours; I wanted to sell the system, not my time.",
 "UC-059": "My policies live in a Word doc and the sign-offs in some lost e-mail — if an audit hits, I have no way to prove anything.",
 "UC-060": "My systems don't talk to each other, and someone spends the day copying data from one tool to another by hand.",
 "UC-061": "I built a prototype that looks great in the demo, but I can't get it actually running in my business.",
 "UC-062": "I don't know whether my numbers are above or below my industry — I compare on gut feel, with nothing to go on.",
 "UC-063": "My app handles sensitive data about real people, and I lose sleep afraid it'll leak or be used wrong.",
 "UC-064": "Approval here is a screenshot in the WhatsApp group — if it's questioned later, I have no solid proof of who signed off on what.",
 "UC-065": "Every department runs a pile of loose spreadsheets and tools, with no control at all over who changed what.",
 "UC-066": "When an external audit arrives, I spend days piecing together screenshots and spreadsheets to prove what happened.",
 "UC-067": "It's an operation that can't go wrong, but today I trust to luck and have no way to prove that each step was checked."
};
