// English marketing titles for the UC catalog — CURATED copy (CMO lens),
// native AmE, outcome/pain-first, no internal taxonomy or acronyms.
// Mirrors src/lib/catalogo-titulos.ts (pt). Rules: never "CRM" for UC-001,
// no competitor names, message-house-en lexicon.

export const TITULOS_CMO_EN: Record<string, string> = {
  // A — Day-to-day operations
  'UC-001': 'From lead to contract, with no one slipping through',
  'UC-002': 'Leads qualified on their own, follow-ups that never forget',
  'UC-003': 'Contracts with approvals, renewals and deadlines under control',
  'UC-004': 'Every new client onboarded right, no step forgotten',
  'UC-005': 'Know who is about to churn — before they do',
  'UC-006': 'Support that resolves, and pulls in your team at the right time',
  'UC-007': 'Collections that never let a due date slip',
  'UC-008': 'Purchasing with requests, approvals and receiving — no paperwork',
  'UC-009': 'Expense reports approved with proof, no receipt chasing',
  'UC-010': 'Projects and deliverables your client can actually see',
  'UC-011': 'Resume screening and interviews that move on their own',
  'UC-012': 'Employees onboarded (and offboarded) with everything ready on day one',
  'UC-013': 'Work orders from dispatch to sign-off, with evidence',
  'UC-014': 'Inventory that warns you before it runs out',
  'UC-015': 'Clean records: no duplicates, no rework',
  'UC-016': 'Ask your data a question — get the report, done',
  'UC-017': 'Suppliers vetted, with documents and reviews up to date',
  'UC-018': 'Internal policies with sign-offs and a trail — no tracking spreadsheet',
  // B — 24/7 agents
  'UC-019': 'Metric out of range? The fix is already underway',
  'UC-020': 'Months-long nurturing that never drops the ball',
  'UC-021': 'Thousands of records processed without losing one',
  'UC-022': 'Relentless follow-up on proposals and pending items',
  'UC-023': 'Renewals handled early — discounts only with your OK',
  'UC-024': 'Reconciliations checked line by line, no surprises',
  'UC-025': 'Customer gone quiet? Reactivation starts on its own',
  'UC-026': 'Month-end close on track, without the scramble',
  // C — Your customers, served
  'UC-027': 'Your customers resolve everything on WhatsApp — nothing to install',
  'UC-028': 'A booking page that is open 24/7',
  'UC-029': 'Orders and quotes coming straight from your website',
  'UC-030': '“Where is my order?” — answered without your team',
  'UC-031': 'A client portal: documents, history and copies, self-served',
  'UC-032': 'Unhappy customer detected — and won back in time',
  'UC-033': 'Automatic updates on the channel your customer prefers',
  'UC-034': 'Every website lead lands straight in your funnel',
  // D — By industry
  'UC-035': 'A clinic with a full calendar and a breathing front desk',
  'UC-036': 'A law firm where deadlines never blow up',
  'UC-037': 'Accounting with monthly document collection on autopilot',
  'UC-038': 'Real estate from listing to signature, no loose ends',
  'UC-039': 'An agency from brief to client approval, without rework',
  'UC-040': 'Schools and courses with enrollment and admin running on their own',
  'UC-041': 'A credit pipeline with analysis and approvals under control',
  'UC-042': 'E-commerce post-sales: returns and exchanges without the queue',
  'UC-043': 'Recurring services with contracts, schedules and work orders on time',
  'UC-044': 'Events from registration to follow-up, without last-minute spreadsheets',
  'UC-045': 'Property management with service requests and delinquency under control',
  'UC-046': 'A gym with sign-ups, renewals and retention on autopilot',
  'UC-047': 'A repair shop with quotes approved by link and live repair status',
  'UC-048': 'Occupational exams summoned, scheduled and reported on time',
  // E — Multi-client (BPO)
  'UC-049': 'One standard finance process for every client you serve',
  'UC-050': 'One remote front desk for N clinics',
  'UC-051': 'Support at scale: the app handles volume, your team the exceptions',
  'UC-052': 'Your methodology replicated in every new client',
  'UC-053': 'Every client’s KPIs in a single view — with consent',
  'UC-054': 'Client portfolios with an aggregated, consented view',
  // F — Vision (declared as a bet)
  'UC-055': 'Accelerators ready to install',
  'UC-056': 'Experts publishing solutions for your industry',
  'UC-057': 'Your consulting practice, packaged as a product',
  'UC-058': 'From service to software: your BPO as a product',
  'UC-059': 'Compliance ready by industry, installable',
  'UC-060': 'Ready-made integrations for the tools you already use',
  'UC-061': 'Built a prototype somewhere else? Here it becomes a self-operating app',
  'UC-062': 'Industry benchmarks, aggregated with consent',
  // G — Built-in guarantees
  'UC-063': 'Sensitive personal data protected out of the box',
  'UC-064': 'Approvals with proof and undo — not screenshots',
  'UC-065': 'Goodbye shadow spreadsheets: governed apps for every team',
  'UC-066': 'An audit trail ready for the external auditor',
  'UC-067': 'Critical operations with double verification and an immutable record',
};
