import { TRUST_RULES_EN } from '@/lib/messages-en';
import {
  maskCNPJ,
  maskCPF,
  maskEmail,
  type Cenario,
  type CenarioId,
  type DemoCopy,
} from '@/lib/demo-copy';

// Rótulo do CTA beta em inglês. O message house EN (messages-en.ts / CTA_EN)
// ainda não fixou este rótulo (aguarda martelo do fundador) — constante local
// até lá, para não editar a fonte canônica nesta fase.
const CTA_BETA = 'I want this for my business';

// ======================= CENÁRIOS (en) =======================
const CENARIOS: Record<CenarioId, Cenario> = {
  // ---------------------------------------------------------------- LEADS (kanban)
  leads: {
    id: 'leads',
    surface: 'kanban',
    pill: '📊 Leads and contracts — a spreadsheet today',
    tema: 'leads and contracts',
    xlsx: 'leads-creators.xlsx (3 tabs · 25 rows)',
    planilhaRead:
      `I read your spreadsheet. The "Leads" tab has 12 leads (columns become fields) · "Creators" has 8 — I spotted ID numbers and I'll protect them right away · "Contracts" has 5, linked to the creators. Your real data comes in — no retyping anything.`,
    espelhoChips: ['Leads', 'Creators', 'Contracts'],
    premissas: [
      { icon: '👥', text: 'Who uses it: **Recruiter · Manager · Legal**' },
      {
        icon: '🔁',
        kind: 'edit',
        before: 'Funnel: **New → Qualified → Proposal → Contract (4 stages)**',
        after: 'Funnel: **New → Qualified → Proposal → Contract → Onboarding**',
        userMsg: 'The funnel is missing an Onboarding stage at the end.',
        ally: "Funnel with 5 stages ✓ — I propose, you correct. That's how it works.",
        addColuna: 'Onboarding',
      },
      { icon: '🔒', text: 'Email and ID number **protected by default**' },
      { icon: '🛡️', text: 'Legal sees **contracts only**' },
      { icon: '⚡', text: 'A contract only goes out **with your OK**' },
    ],
    ajusteLabel: 'Accepted, with your tweak to the funnel',
    desenho: [
      { icon: '🗃️', label: 'Your data', text: 'Leads, creators and contracts — linked together, with the 25 records from your spreadsheet' },
      { icon: '🖥️', label: 'Your screen', text: 'A visual pipeline by stage — each role on the team sees its own version' },
      { icon: '🤖', label: 'Your assistant', text: 'Suggests and runs the next step on each lead — and asks before the things that matter' },
      { icon: '🔁', label: 'Automation', text: 'Contract signed → onboarding fires on its own' },
      { icon: '🔌', label: 'Connection', text: 'Gmail to send proposals and contracts' },
      { icon: '🛡️', label: 'Who sees what', text: 'Legal only sees contracts · ID numbers and email protected' },
    ],
    buildSteps: [
      'Storing your data — 12 leads, 8 creators, 5 contracts',
      'Setting up who-sees-what in the same move — nothing is born unprotected',
      'Building your pipeline screen',
      'Wiring up the assistant and the automation',
      'Checking everything from the inside — every piece matches the design',
    ],
    columns: ['New', 'Qualified', 'Proposal', 'Contract'],
    extraN: 7,
    seed: [
      { id: 'ana', name: 'Anna Reed', stage: 'New', meta: { empresa: 'TechFin', email: 'anna@techfin.com' } },
      { id: 'bruno', name: 'Brian Cole', stage: 'New', meta: { empresa: 'AgroData', email: 'brian@agrodata.io' } },
      { id: 'carla', name: 'Claire Bennett', stage: 'New', meta: { empresa: 'FinOps Lab', email: 'claire@finopslab.com' } },
      { id: 'diego', name: 'Dylan Price', stage: 'New', meta: { empresa: 'EduPlay', email: 'dylan@eduplay.com' } },
      { id: 'elisa', name: 'Elise Grant', stage: 'New', meta: { empresa: 'HealthHub', email: 'elise@healthhub.co' } },
    ],
    autoMove: { id: 'bruno', toStage: 'Qualified', log: 'Assistant qualified this — next step suggested' },
    nbaDefault: (r) => ({
      text:
        r.stage === 'New'
          ? 'Qualify this lead — the data came in complete.'
          : r.stage === 'Contract'
            ? 'Follow up on the signature — contract sent.'
            : 'Move to the next stage of the funnel.',
    }),
    appTitle: 'Leads Pipeline',
    boardLabel: 'Pipeline',
    ctaObj: 'an app',
    subtitle: (r) => `${r.meta.empresa} · ${maskEmail(r.meta.email)}`,
    recordFields: (r) => [
      { label: 'Name', value: r.name },
      { label: 'Company', value: r.meta.empresa },
      { label: 'Email', value: maskEmail(r.meta.email), lock: true },
      { label: 'Stage', value: r.stage },
      { label: 'Owner', value: 'Recruiter (you)' },
    ],
    tableCols: [
      { header: 'Name', get: (r) => r.name, primary: true },
      { header: 'Company', get: (r) => r.meta.empresa },
      { header: 'Email', get: (r) => maskEmail(r.meta.email), lock: true },
      { header: 'Stage', stage: true },
    ],
    newForm: {
      title: 'New lead',
      add: '+ New lead',
      fields: [
        { label: 'Name', def: 'Grant Ellis' },
        { label: 'Company', def: 'RetailPro' },
        { label: 'Email', def: 'grant@retailpro.com' },
      ],
      build: (v) => ({
        name: v[0] || 'Grant Ellis',
        meta: { empresa: v[1] || 'RetailPro', email: v[2] || 'grant@retailpro.com' },
      }),
    },
    magic:
      'The leads from your spreadsheet are already on screen. Play around: click a name, create a lead, move a card.',
    touchHint: 'create or move a lead, open a record',
    hitl: {
      text: 'The contract for **Anna Reed (TechFin)** is ready. Send it via Gmail?',
      button: 'Approve send',
      note: 'You approved: contract for Anna Reed',
      lead: "Contract's out.",
      resolveLabel: 'You approved the send',
      apply: { id: 'ana', toStage: 'Contract', log: 'Contract sent via Gmail — approved by you' },
    },
    evolve: {
      userMsg: 'Add a Negotiation stage before Contract.',
      col: 'Negotiation',
      before: 'Contract',
      allyViaChat:
        'This is how you evolve it — by asking. In this demo I apply a ready-made example: a Negotiation stage before Contract. Look at the pipeline:',
      doneLabel: 'Negotiation stage in the pipeline',
    },
  },

  // ---------------------------------------------------------------- CAIXA (financeiro)
  caixa: {
    id: 'caixa',
    surface: 'financeiro',
    pill: '💰 Accounts receivable and collections — a spreadsheet today',
    tema: 'accounts receivable and collections',
    xlsx: 'accounts-receivable.xlsx (2 tabs · 22 rows)',
    planilhaRead:
      `I read your spreadsheet. The "Invoices" tab has 14 invoices (columns become fields: client, amount, due date) · "Clients" has 8 — I spotted a tax ID and I'll protect it right away. Got it: track receivables, due dates and the collections cadence — a spreadsheet today. Your real data comes in — no retyping anything.`,
    espelhoChips: ['Invoices', 'Clients', 'Collections'],
    premissas: [
      {
        icon: '🔔',
        kind: 'edit',
        before: 'Collections cadence in **3 touches** (reminder → dunning → settlement offer)',
        after: 'Collections cadence in **4 touches** (friendly heads-up → reminder → dunning → settlement offer)',
        userMsg: "Before the dunning there's a friendly heads-up — my cadence has 4 touches.",
        ally: 'Cadence with 4 touches ✓ — I propose, you correct.',
      },
      { icon: '✋', text: 'Discounts above **5% only with your approval** (a human decision)' },
      { icon: '👁️', text: 'Amounts visible **only to the Finance role**' },
      { icon: '🔒', text: 'Tax ID and email **protected by default**' },
    ],
    ajusteLabel: 'Accepted, with your tweak to the cadence',
    desenho: [
      { icon: '🗃️', label: 'Your data', text: 'Invoices, clients and collections linked, with the 22 records from the spreadsheet' },
      { icon: '🖥️', label: 'Your screen', text: 'A receivables dashboard by status, with the total at risk up top' },
      { icon: '🤖', label: 'Your assistant', text: 'Prioritizes who to chase, drafts the message — and asks before sending' },
      { icon: '🔁', label: 'Automation', text: 'Due date hits → the cadence fires on its own' },
      { icon: '🔌', label: 'Connection', text: 'Gmail and WhatsApp for reminders and dunning' },
      { icon: '🛡️', label: 'Who sees what', text: 'Amounts only for Finance · tax ID protected' },
    ],
    buildSteps: [
      'Storing your data — 14 invoices, 8 clients, collections',
      'Protecting tax IDs and amounts in the same move — nothing is born unprotected',
      'Building your receivables screen',
      'Wiring up the assistant and the collections cadence',
      'Checking everything from the inside — every piece matches the design',
    ],
    columns: ['Due soon', 'Overdue', 'In negotiation', 'Paid'],
    extraN: 9,
    seed: [
      {
        id: 'techfin',
        name: 'TechFin',
        stage: 'Due soon',
        meta: { valor: '$12,400', venc: 'due tomorrow', email: 'finance@techfin.com', cnpj: '11.222.333/0001-81' },
        nba: { text: 'Friendly reminder — the invoice is due tomorrow.', kind: 'note', log: 'Reminder sent ✓ — the invoice is due tomorrow.' },
      },
      { id: 'agro', name: 'AgroData', stage: 'Overdue', meta: { valor: '$8,900', venc: '12 days overdue', email: 'finance@agrodata.io', cnpj: '44.555.666/0001-72' } },
      { id: 'finops', name: 'FinOps Lab', stage: 'In negotiation', meta: { valor: '$21,000', venc: 'in negotiation', email: 'billing@finopslab.com', cnpj: '77.888.999/0001-63' } },
      { id: 'eduplay', name: 'EduPlay', stage: 'Due soon', meta: { valor: '$5,600', venc: 'due in 6 days', email: 'finance@eduplay.com', cnpj: '22.333.444/0001-54' } },
      { id: 'healthhub', name: 'HealthHub', stage: 'Overdue', meta: { valor: '$3,100', venc: '3 days overdue', email: 'finance@healthhub.co', cnpj: '55.666.777/0001-45' } },
    ],
    touchId: 'techfin',
    autoMove: { id: 'healthhub', toStage: 'In negotiation', log: 'Assistant prioritized the collection — next step suggested' },
    nbaDefault: () => ({ text: 'Send the next touch in the cadence — track the due date.', kind: 'note', log: 'Reminder sent ✓ — tracking the due date.' }),
    appTitle: 'Accounts Receivable',
    boardLabel: 'Invoices',
    ctaObj: 'a collection',
    subtitle: (r) => `${r.meta.valor} · ${r.meta.venc}`,
    recordFields: (r) => [
      { label: 'Client', value: r.name },
      { label: 'Amount', value: r.meta.valor },
      { label: 'Due date', value: r.meta.venc },
      { label: 'Tax ID', value: maskCNPJ(r.meta.cnpj), lock: true },
      { label: 'Email', value: maskEmail(r.meta.email), lock: true },
      { label: 'Status', value: r.stage },
      { label: 'Owner', value: 'Finance (you)' },
    ],
    tableCols: [
      { header: 'Client', get: (r) => r.name, primary: true },
      { header: 'Amount', get: (r) => r.meta.valor },
      { header: 'Due date', get: (r) => r.meta.venc },
      { header: 'Status', stage: true },
    ],
    newForm: {
      title: 'New invoice',
      add: '+ New invoice',
      fields: [
        { label: 'Client', def: 'Contoso' },
        { label: 'Amount', def: '$4,200' },
        { label: 'Due date', def: 'due in 15 days' },
      ],
      build: (v) => ({
        name: v[0] || 'Contoso',
        meta: {
          valor: v[1] || '$4,200',
          venc: v[2] || 'due in 15 days',
          email: 'finance@contoso.com',
          cnpj: '99.888.777/0001-66',
        },
      }),
    },
    magic:
      'The invoices from your spreadsheet are already on screen, with the total at risk up top. Play around: click a stat to filter, open an invoice.',
    touchHint: 'open an invoice or click a stat to filter',
    hitl: {
      text: 'The **AgroData ($8,900)** invoice is 12 days overdue. I drafted the dunning with a 2-installment payment plan — send it?',
      button: 'Approve send',
      note: 'You approved: collection for AgroData',
      lead: 'Dunning sent.',
      resolveLabel: 'You approved the send',
      apply: { id: 'agro', toStage: 'In negotiation', log: 'Dunning sent with a payment plan — approved by you' },
    },
    evolve: {
      userMsg: 'Add a Settlement stage before Paid.',
      col: 'Settlement',
      before: 'Paid',
      move: { id: 'finops', from: 'In negotiation', to: 'Settlement', log: 'Moved to Settlement — payment plan agreed with the client' },
      allyViaChat:
        'This is how you evolve it — by asking. In this demo I apply a ready-made example: a Settlement status before Paid. Look at the dashboard:',
      doneLabel: 'Settlement status in the cadence',
    },
  },

  // ---------------------------------------------------------------- ATENDIMENTO (chats)
  atendimento: {
    id: 'atendimento',
    surface: 'chats',
    pill: '📅 WhatsApp support that resolves — a schedule buried in messages',
    tema: 'WhatsApp support',
    xlsx: 'patients.xlsx (2 tabs · 20 rows)',
    planilhaRead:
      `I read your spreadsheet. The "Patients" tab has 15 patients (columns become fields) · "Insurance" has 5 — I spotted ID numbers and I'll protect them right away. Got it: handle WhatsApp, book and reschedule appointments and confirm attendance — today one person answers everything, all day long. Your real data comes in — no retyping anything.`,
    espelhoChips: ['Patients', 'Schedule', 'Conversations'],
    premissas: [
      {
        icon: '🕒',
        kind: 'edit',
        before: 'Support **Mon–Fri, 8am–6pm**',
        after: 'Support **Mon–Fri 8am–6pm + Saturday until 12pm**',
        userMsg: 'We have appointments on Saturday mornings too.',
        ally: 'Saturday until 12pm ✓ — noted.',
      },
      { icon: '🤖', text: 'The assistant **books, reschedules and confirms on its own**' },
      { icon: '🚨', text: 'Clinical matters or emergencies → **a person takes over right away**' },
      { icon: '🔒', text: 'Health data **never travels through the chat**' },
    ],
    ajusteLabel: 'Accepted, with your tweak to the hours',
    desenho: [
      { icon: '🗃️', label: 'Your data', text: 'Patients, schedule and conversations linked, with the 20 records from the spreadsheet' },
      { icon: '🖥️', label: 'Your screen', text: "A conversation queue by status, with the day's schedule alongside" },
      { icon: '🤖', label: 'Your assistant', text: 'It handles and acts: books, reschedules, confirms — not a chat that just replies' },
      { icon: '🔁', label: 'Automation', text: 'Appointment booked → automatic confirmation the day before' },
      { icon: '🔌', label: 'Connection', text: 'WhatsApp and calendar (Google Calendar)' },
      { icon: '🛡️', label: 'Who sees what', text: 'Clinical matters only for the team · ID number protected' },
    ],
    buildSteps: [
      'Storing your data — 15 patients, schedule, conversations',
      'Protecting ID numbers and health data in the same move — nothing is born unprotected',
      'Building your conversation queue',
      'Wiring up the assistant and the automatic confirmations',
      'Checking everything from the inside — every piece matches the design',
    ],
    columns: ['New', 'In progress', 'Awaiting patient', 'Resolved'],
    extraN: 8,
    seed: [
      {
        id: 'marina',
        name: 'Megan Foster',
        stage: 'New',
        meta: { pedido: 'wants to reschedule to Thursday', cpf: '123.456.789-01' },
        thread: [
          { who: 'user', text: 'Hi, I need to reschedule my appointment 🙏', time: '09:12' },
          { who: 'user', text: 'Can I move it to Thursday?', time: '09:12' },
        ],
        nba: { text: 'Reschedule to Thursday at 2pm and confirm on the calendar.', kind: 'advance', log: "Done! Rescheduled to Thursday, 2pm ✓ I've updated your calendar." },
      },
      {
        id: 'jose',
        name: 'Jason Brooks',
        stage: 'New',
        meta: { pedido: 'first appointment, asked for a time', cpf: '234.567.890-12' },
        thread: [
          { who: 'user', text: "Hi, I'd like to book a first appointment", time: '10:03' },
          { who: 'agent', text: 'Of course! I have tomorrow at 10am or Thursday at 2pm. Which works better?', time: '10:03' },
          { who: 'user', text: 'Tomorrow 10am', time: '10:05' },
        ],
      },
      {
        id: 'paula',
        name: 'Paula Hughes',
        stage: 'In progress',
        meta: { pedido: 'asked about a test result', cpf: '345.678.901-23' },
        thread: [{ who: 'user', text: 'Hi, are my blood test results in?', time: '11:20' }],
        nba: {
          text: "Clinical matter — the assistant doesn't answer: hand off to the team now.",
          kind: 'handoff',
          log: "🙋 Clinical matter — the assistant doesn't answer: handed off to the team.",
        },
      },
      {
        id: 'carlos',
        name: 'Carl Dawson',
        stage: 'Awaiting patient',
        meta: { pedido: 'confirm attendance tomorrow', cpf: '456.789.012-34' },
        thread: [
          { who: 'agent', text: 'Hi, Carl! Just a reminder about your appointment tomorrow at 3pm. Can you confirm?', time: '08:30' },
          { who: 'user', text: "Confirmed, I'll be there 👍", time: '08:41' },
          { who: 'agent', text: 'Perfect, attendance confirmed ✓ See you tomorrow!', time: '08:41' },
        ],
      },
      {
        id: 'rita',
        name: 'Rita Morgan',
        stage: 'New',
        meta: { pedido: 'insurance question', cpf: '567.890.123-45' },
        thread: [{ who: 'user', text: 'Do you take Aetna insurance?', time: '14:02' }],
      },
    ],
    touchId: 'jose',
    autoMove: { id: 'rita', toStage: 'In progress', log: 'Yes, we take Aetna! Want me to book you in? ✓' },
    nbaDefault: () => ({ text: 'Reply and book — the assistant resolves and confirms.', kind: 'advance', log: 'Replied and moved forward ✓' }),
    appTitle: 'Support — WhatsApp',
    boardLabel: 'Queue',
    ctaObj: 'a support flow',
    subtitle: (r) => r.meta.pedido,
    recordFields: (r) => [
      { label: 'Patient', value: r.name },
      { label: 'Request', value: r.meta.pedido },
      { label: 'ID number', value: maskCPF(r.meta.cpf), lock: true },
      { label: 'Status', value: r.stage },
      { label: 'Owner', value: 'Agent (you)' },
    ],
    tableCols: [
      { header: 'Patient', get: (r) => r.name, primary: true },
      { header: 'Request', get: (r) => r.meta.pedido },
      { header: 'Status', stage: true },
    ],
    newForm: {
      title: 'New conversation',
      add: '+ New conversation',
      fields: [
        { label: 'Patient', def: 'Lucas Allen' },
        { label: 'Request', def: 'wants to book an assessment' },
        { label: 'ID number', def: '678.901.234-56' },
      ],
      build: (v) => ({
        name: v[0] || 'Lucas Allen',
        meta: { pedido: v[1] || 'wants to book an assessment', cpf: v[2] || '678.901.234-56' },
      }),
    },
    magic:
      'The conversations from your spreadsheet are already in the queue. Play around: open a conversation and watch the assistant at work — it books, confirms and hands clinical cases to the team.',
    touchHint: 'open a conversation in the queue',
    hitl: {
      text: '**Jason asked for a first appointment tomorrow at 10am** — the calendar is open. Should I confirm the booking?',
      button: 'Confirm booking',
      note: "You approved: Jason's appointment confirmed",
      lead: 'Appointment confirmed.',
      resolveLabel: 'You confirmed the booking',
      apply: { id: 'jose', toStage: 'Awaiting patient', log: 'Booked! Tomorrow at 10am ✓ Confirmation sent.' },
    },
    evolve: {
      userMsg: 'Turn on automatic confirmation the day before.',
      regra: '🔔 confirms day before ✓',
      allyViaChat:
        'This is how you evolve it — by asking. In this demo I turn on a ready-made example: automatic confirmation the day before. Look at the support rules:',
      doneLabel: 'automatic confirmation the day before',
    },
  },
};

export const DEMO_COPY_EN: DemoCopy = {
  brandHref: '/en',
  stages: ['Mirror', 'Frame', 'Design', 'Living draft', 'Is this it?', 'Operate', 'Publish', 'Evolve'],
  statusColor: {
    New: 'blue',
    'In progress': 'amber',
    'Awaiting patient': 'violet',
    Resolved: 'green',
    'Due soon': 'blue',
    Overdue: 'red',
    'In negotiation': 'amber',
    Settlement: 'violet',
    Paid: 'green',
  },
  currency: (n) => '$' + n.toLocaleString('en-US'),
  route: {
    caixa: /invoice|receivable|collect|overdue|billing|payment|dunning|cash/,
    atendimento: /support|appointment|booking|schedul|whatsapp|patient|clinic/,
  },
  entry: {
    greeting:
      "Hi! I'm Ally 👋 Pick an example below — or tell me a problem in your business in your own words, and I'll read how you work today. Both paths work.",
    examples: [
      'my leads and contracts live in a spreadsheet…',
      'chasing overdue invoices, all in a spreadsheet…',
      'my clinic is drowning in WhatsApp messages…',
    ],
  },
  cenarios: CENARIOS,
  trustRules: TRUST_RULES_EN,
  ctaBeta: CTA_BETA,

  flow: {
    prosaAlly: (tema) =>
      `Nice! This is exactly how it works: you write, I understand and build. In this demo I follow a ready-made example — ${tema} — but the path is the same with YOUR problem. Take a look:`,
    resolvedEspelho: 'Confirmed by you',
    allyConfirmaFunciona: "So let me confirm how your business works — correct only what's wrong:",
    enquadrarAceito: 'Accepted as proposed',
    allyDesenhei: 'I designed your whole app. In plain English, not jargon:',
    resolvedDesenho: 'You asked me to build it',
    origemPlanilha: 'from your spreadsheet',
    importadoPlanilha: (arquivo) => `Imported from ${arquivo}`,
    allyAppDePe: (magic) => `🎉 Your app is up — as a draft, only yours. ${magic} Then tell me if this is it.`,
    allyExperimenta: (touchHint) =>
      `Try playing with the app first — ${touchHint}. Deciding by seeing is the deal. 😉`,
    resolvedGate: 'You kept it — decided by seeing',
    noteAppAprovado: (time) => `App approved by you, watching it work · ${time}`,
    allyAssumeDia: 'Now Ally takes over the day-to-day — and asks you before the things that matter. Watch her work:',
    ajustarUserMsg: (alvo, entryCol) => `I'd like ${alvo} right after ${entryCol}.`,
    allyTroquei: 'Swapped — look at the screen. Adjusting a draft is a conversation, not rework. Is this it?',
    allyDescartar:
      "If you discard, I remove EVERYTHING in the draft — nothing is left in your space. (In this demo, I'll stay here in case you change your mind.)",
    allyAutomacaoSegue: (lead) =>
      `${lead} The automation runs to the end and stays on the record. Before opening it to your team, I prove from the inside that each role sees only what was agreed — then you publish:`,
    resolvedPublicar: 'Published to the team',
    allyAppVivo: '🏁 App live, governed and working. From here on, evolving is just a conversation — give it a try:',
    allyAplicado: "Applied ✓ — a simple change needs no ceremony. And there's Undo, because mistakes must never hurt.",
    allyAnotei:
      'Noted! In the product this is exactly how it works: you write, I do it. In this demo I follow a script — the next decision is in the card just above (or use the ▶ arrows up top).',
    resolvedHitlLater: 'Left for later — stays in your queue',
    logVoceMoveu: (next) => `You moved to ${next}`,
    logCriadoDireto: 'Created by you, right in the draft',
    origemCriado: 'created by you',
    logEncaminhado: 'Handed off to a human',
    logFeito: 'Done ✓',
    logProximoPasso: 'Next step done by the assistant — with your OK',
  },

  cards: {
    espelhoKick: 'Mirror — is this it?',
    espelhoChipNew: 'brand-new app — nothing you already have covers this',
    espelhoBtn: "That's it ✓",
    enquadrarKick: 'Confirm how it works — correct by exception',
    ajustadoPorVoce: '(adjusted by you)',
    corrigir: 'fix',
    enquadrarBtn: "That's right →",
    desenhoKick: "Your app's design",
    desenhoVerified: '✓ internal check: design complete and coherent, end to end',
    desenhoBtn: 'Build the draft so I can see it →',
    gateKick: 'Your call — looking at the real thing',
    gateP:
      'You decide by **seeing and using it**, not by approving a technical checklist. Adjusting is cheap; discarding removes everything, no leftovers.',
    gateKeep: 'Keep it ✓',
    gateAdjust: 'Adjust',
    gateDiscard: 'Discard',
    hitlKick: 'Your call — Ally waits',
    hitlLater: 'Not now',
    publicarKick: 'Open it to the team?',
    publicarP:
      'Proven from the inside before exposing it: each role sees exactly what was agreed, sensitive data protected, automation checked — **in the database, not on paper**.',
    publicarBtn: 'Publish to the team',
    evoluirKick: 'Evolving is just talking',
    evoluirApplied: 'Applied ✓',
    desfazer: 'Undo',
    evoluirReverted: "↩︎ Reverted by you — without losing any data. **Mistakes don't hurt.**",
    ctaKick: 'This, with YOUR data',
    ctaP: (ctaObj) =>
      `You just created, approved by seeing, and operated ${ctaObj} — with sample data. With your real spreadsheet, the path is the same.`,
    buildKick: 'Building your draft — zero questions',
  },

  app: {
    assistenteMoveu: 'assistant moved',
    mover: 'move →',
    moverAria: (name) => `Move ${name}`,
    maisDaPlanilha: (n) => `+${n} from the spreadsheet`,
    finEmAberto: 'Open',
    finVencido: 'Overdue',
    finEmNegociacao: 'In negotiation',
    limparFiltro: 'clear filter',
    finContador: (n) => `${n} invoices · tap a stat to filter`,
    finTableHead: ['Client', 'Amount', 'Due date', 'Status'],
    abrir: 'open →',
    nenhumaFatura: 'No invoices in this filter.',
    regrasAtendimentoAria: 'Support rules',
    regraAgenda: '🤖 books on its own ✓',
    regraClinico: '🙋 clinical → human ✓',
    novo: 'NEW',
    naoLidaAria: 'unread',
    maisConversas: (n) => `+${n} conversations from the spreadsheet`,
    humanoAssume: '🙋 Human takes over',
    sugestaoAssistente: '🤖 Assistant suggestion',
    proximoPassoSugerido: '🤖 Suggested next step',
    fazerIsso: 'Do this',
    protegidoTitle: 'Protected: your role sees it masked — decided in the design',
    historico: 'History — everything is logged',
    badgeDraft: 'draft — only you can see it',
    badgeKept: 'approved by you',
    badgePub: 'published to the team',
    appAria: 'Your app',
    emptyTitle: 'Your app will appear here',
    emptySub: 'first as a draft — you approve what you see.',
    viewModeAria: 'View mode',
    tabela: 'Table',
    buscarPlaceholder: 'Search…',
    buscarAria: 'Search records',
    tabelaContador: (shown, total) => `${shown} shown · ${total} total`,
    trustAria: 'Trust rules shown',
  },

  shell: {
    brandAria: 'Back to the Fluxomind site',
    crumbCompany: 'your-company',
    crumbTitle: 'Creation journey',
    navAria: 'Navigate the journey step by step',
    voltarPasso: 'Back one step',
    passoAPasso: 'step by step',
    avancarPasso: 'Forward one step',
    recomecarTitle: 'Restart the demo and pick another example',
    recomecar: ' Start over',
    phaseFull: 'demo · product in the making',
    phaseShort: 'in the making',
    ctaShort: 'I want this',
    railAria: 'Journey stages',
    conversaAria: 'Conversation',
    you: 'You',
    inputStarted: 'Type here — e.g. add a stage to the funnel…',
    inputIdle: 'Or describe your business problem in your own words…',
    inputAria: 'Message to Ally',
    enviarAria: 'Send message',
    panebarAria: 'Switch between conversation and app',
    paneChat: '💬 Conversation',
    paneApp: '▦ Your app',
    decisaoPendenteAria: 'pending decision',
    novidadeAria: 'new in the app',
    honest:
      'Interactive demo with sample data — it illustrates the creation journey; the real app is born inside the platform, with your data.',
    modalProtegido: '🛡️ Becomes a real record in your space — protected and yours only.',
    criar: 'Create',
    cancelar: 'Cancel',
  },
};
