import { TRUST_RULES, CTA } from '@/lib/messages';
import {
  maskCNPJ,
  maskCPF,
  maskEmail,
  type Cenario,
  type CenarioId,
  type DemoCopy,
} from '@/lib/demo-copy';

// ======================= CENÁRIOS (pt) =======================
const CENARIOS: Record<CenarioId, Cenario> = {
  // ---------------------------------------------------------------- LEADS (kanban)
  leads: {
    id: 'leads',
    surface: 'kanban',
    pill: '📊 Leads e contratos — hoje é planilha',
    tema: 'leads e contratos',
    xlsx: 'leads-criadores.xlsx (3 abas · 25 linhas)',
    planilhaRead:
      'Li sua planilha. A aba "Leads" tem 12 leads (colunas viram campos) · "Criadores" tem 8 — detectei CPF e já vou proteger · "Contratos" tem 5, ligados aos criadores. Seus dados entram de verdade, sem redigitar nada.',
    espelhoChips: ['Leads', 'Criadores', 'Contratos'],
    premissas: [
      { icon: '👥', text: 'Quem usa: **Recrutador · Gestor · Jurídico**' },
      {
        icon: '🔁',
        kind: 'edit',
        before: 'Funil: **Novo → Qualificado → Proposta → Contrato (4 etapas)**',
        after: 'Funil: **Novo → Qualificado → Proposta → Contrato → Onboarding**',
        userMsg: 'Falta a etapa de Onboarding no fim do funil.',
        ally: 'Funil com 5 etapas ✓ — eu proponho, você corrige. É assim que funciona.',
        addColuna: 'Onboarding',
      },
      { icon: '🔒', text: 'E-mail e CPF **protegidos por padrão**' },
      { icon: '🛡️', text: 'Jurídico vê **só contratos**' },
      { icon: '⚡', text: 'Contrato só sai **com o seu OK**' },
    ],
    ajusteLabel: 'Aceito, com seu ajuste no funil',
    desenho: [
      { icon: '🗃️', label: 'Seus dados', text: 'Leads, criadores e contratos — ligados entre si, com os 25 registros da sua planilha' },
      { icon: '🖥️', label: 'Sua tela', text: 'Um pipeline visual por etapa — cada papel da equipe vê a sua versão' },
      { icon: '🤖', label: 'Seu assistente', text: 'Sugere e executa o próximo passo em cada lead — e pergunta antes do que importa' },
      { icon: '🔁', label: 'Automação', text: 'Contrato assinado → onboarding dispara sozinho' },
      { icon: '🔌', label: 'Conexão', text: 'Gmail para enviar propostas e contratos' },
      { icon: '🛡️', label: 'Quem vê o quê', text: 'Jurídico só vê contratos · CPF e e-mail protegidos' },
    ],
    buildSteps: [
      'Guardando seus dados — 12 leads, 8 criadores, 5 contratos',
      'Protegendo quem-vê-o-quê no mesmo ato — nada nasce desprotegido',
      'Montando sua tela de pipeline',
      'Ligando o assistente e a automação',
      'Conferindo tudo por dentro — cada peça bate com o desenho',
    ],
    columns: ['Novo', 'Qualificado', 'Proposta', 'Contrato'],
    extraN: 7,
    seed: [
      { id: 'ana', name: 'Ana Souza', stage: 'Novo', meta: { empresa: 'TechFin', email: 'ana@techfin.com' } },
      { id: 'bruno', name: 'Bruno Lima', stage: 'Novo', meta: { empresa: 'AgroData', email: 'bruno@agrodata.io' } },
      { id: 'carla', name: 'Carla Mendes', stage: 'Novo', meta: { empresa: 'FinOps Lab', email: 'carla@finopslab.com' } },
      { id: 'diego', name: 'Diego Rocha', stage: 'Novo', meta: { empresa: 'EduPlay', email: 'diego@eduplay.com' } },
      { id: 'elisa', name: 'Elisa Prado', stage: 'Novo', meta: { empresa: 'HealthHub', email: 'elisa@healthhub.co' } },
    ],
    autoMove: { id: 'bruno', toStage: 'Qualificado', log: 'Assistente qualificou — próximo passo sugerido' },
    nbaDefault: (r) => ({
      text:
        r.stage === 'Novo'
          ? 'Qualificar este lead — os dados vieram completos.'
          : r.stage === 'Contrato'
            ? 'Acompanhar a assinatura — contrato enviado.'
            : 'Avançar para a próxima etapa do funil.',
    }),
    appTitle: 'Pipeline de Leads',
    boardLabel: 'Pipeline',
    ctaObj: 'um app',
    subtitle: (r) => `${r.meta.empresa} · ${maskEmail(r.meta.email)}`,
    recordFields: (r) => [
      { label: 'Nome', value: r.name },
      { label: 'Empresa', value: r.meta.empresa },
      { label: 'E-mail', value: maskEmail(r.meta.email), lock: true },
      { label: 'Etapa', value: r.stage },
      { label: 'Dono', value: 'Recrutador (você)' },
    ],
    tableCols: [
      { header: 'Nome', get: (r) => r.name, primary: true },
      { header: 'Empresa', get: (r) => r.meta.empresa },
      { header: 'E-mail', get: (r) => maskEmail(r.meta.email), lock: true },
      { header: 'Etapa', stage: true },
    ],
    newForm: {
      title: 'Novo lead',
      add: '+ Novo lead',
      fields: [
        { label: 'Nome', def: 'Gustavo Reis' },
        { label: 'Empresa', def: 'RetailPro' },
        { label: 'E-mail', def: 'gustavo@retailpro.com' },
      ],
      build: (v) => ({
        name: v[0] || 'Gustavo Reis',
        meta: { empresa: v[1] || 'RetailPro', email: v[2] || 'gustavo@retailpro.com' },
      }),
    },
    magic:
      'Os leads da planilha já estão na tela. Mexe à vontade: clique num nome, crie um lead, mova um card.',
    touchHint: 'cria ou move um lead, abre uma ficha',
    hitl: {
      text: 'O contrato da **Ana Souza (TechFin)** está pronto. Envio por Gmail?',
      button: 'Aprovar envio',
      note: 'Você aprovou: contrato para Ana Souza',
      lead: 'Contrato foi.',
      resolveLabel: 'Você aprovou o envio',
      apply: { id: 'ana', toStage: 'Contrato', log: 'Contrato enviado por Gmail — aprovado por você' },
    },
    evolve: {
      userMsg: 'Adiciona a etapa Negociação antes de Contrato.',
      col: 'Negociação',
      before: 'Contrato',
      allyViaChat:
        'É assim que se evolui — pedindo. Nesta demonstração eu aplico um exemplo pronto: a etapa Negociação antes de Contrato. Olha o pipeline:',
      doneLabel: 'etapa Negociação no pipeline',
    },
  },

  // ---------------------------------------------------------------- CAIXA (financeiro)
  caixa: {
    id: 'caixa',
    surface: 'financeiro',
    pill: '💰 Contas a receber e cobrança — hoje é planilha',
    tema: 'contas a receber e cobrança',
    xlsx: 'contas-a-receber.xlsx (2 abas · 22 linhas)',
    planilhaRead:
      'Li sua planilha. A aba "Faturas" tem 14 faturas (colunas viram campos: cliente, valor, vencimento) · "Clientes" tem 8 — detectei CNPJ e já vou proteger. Entendi: acompanhar faturas a receber, vencimentos e a régua de cobrança — hoje numa planilha. Seus dados entram de verdade, sem redigitar nada.',
    espelhoChips: ['Faturas', 'Clientes', 'Cobranças'],
    premissas: [
      {
        icon: '🔔',
        kind: 'edit',
        before: 'Régua de cobrança em **3 toques** (lembrete → cobrança → proposta de acordo)',
        after: 'Régua de cobrança em **4 toques** (aviso amigável → lembrete → cobrança → proposta de acordo)',
        userMsg: 'Antes da cobrança tem um aviso amigável — minha régua tem 4 toques.',
        ally: 'Régua com 4 toques ✓ — eu proponho, você corrige.',
      },
      { icon: '✋', text: 'Desconto acima de **5% só com sua aprovação** (decisão humana)' },
      { icon: '👁️', text: 'Valores visíveis **só para o papel Financeiro**' },
      { icon: '🔒', text: 'CNPJ e e-mail **protegidos por padrão**' },
    ],
    ajusteLabel: 'Aceito, com seu ajuste na régua',
    desenho: [
      { icon: '🗃️', label: 'Seus dados', text: 'Faturas, clientes e cobranças ligados, com os 22 registros da planilha' },
      { icon: '🖥️', label: 'Sua tela', text: 'Painel de recebíveis por status, com o total em risco no topo' },
      { icon: '🤖', label: 'Seu assistente', text: 'Prioriza quem cobrar, redige a mensagem — e pergunta antes de enviar' },
      { icon: '🔁', label: 'Automação', text: 'Vencimento chegou → a régua dispara sozinha' },
      { icon: '🔌', label: 'Conexão', text: 'Gmail e WhatsApp para lembretes e cobranças' },
      { icon: '🛡️', label: 'Quem vê o quê', text: 'Valores só para o Financeiro · CNPJ protegido' },
    ],
    buildSteps: [
      'Guardando seus dados — 14 faturas, 8 clientes, cobranças',
      'Protegendo CNPJ e valores no mesmo ato — nada nasce desprotegido',
      'Montando sua tela de recebíveis',
      'Ligando o assistente e a régua de cobrança',
      'Conferindo tudo por dentro — cada peça bate com o desenho',
    ],
    columns: ['A vencer', 'Vencida', 'Em negociação', 'Paga'],
    extraN: 9,
    seed: [
      {
        id: 'techfin',
        name: 'TechFin',
        stage: 'A vencer',
        meta: { valor: 'R$ 12.400', venc: 'vence amanhã', email: 'financeiro@techfin.com', cnpj: '11.222.333/0001-81' },
        nba: { text: 'Lembrete amigável — a fatura vence amanhã.', kind: 'note', log: 'Lembrete enviado ✓ — a fatura vence amanhã.' },
      },
      { id: 'agro', name: 'AgroData', stage: 'Vencida', meta: { valor: 'R$ 8.900', venc: 'vencida há 12 dias', email: 'financeiro@agrodata.io', cnpj: '44.555.666/0001-72' } },
      { id: 'finops', name: 'FinOps Lab', stage: 'Em negociação', meta: { valor: 'R$ 21.000', venc: 'em negociação', email: 'contas@finopslab.com', cnpj: '77.888.999/0001-63' } },
      { id: 'eduplay', name: 'EduPlay', stage: 'A vencer', meta: { valor: 'R$ 5.600', venc: 'vence em 6 dias', email: 'financeiro@eduplay.com', cnpj: '22.333.444/0001-54' } },
      { id: 'healthhub', name: 'HealthHub', stage: 'Vencida', meta: { valor: 'R$ 3.100', venc: 'vencida há 3 dias', email: 'financeiro@healthhub.co', cnpj: '55.666.777/0001-45' } },
    ],
    touchId: 'techfin',
    autoMove: { id: 'healthhub', toStage: 'Em negociação', log: 'Assistente priorizou a cobrança — próximo passo sugerido' },
    nbaDefault: () => ({ text: 'Enviar o próximo toque da régua — acompanhar o vencimento.', kind: 'note', log: 'Lembrete enviado ✓ — acompanhando o vencimento.' }),
    appTitle: 'Contas a Receber',
    boardLabel: 'Faturas',
    ctaObj: 'uma cobrança',
    subtitle: (r) => `${r.meta.valor} · ${r.meta.venc}`,
    recordFields: (r) => [
      { label: 'Cliente', value: r.name },
      { label: 'Valor', value: r.meta.valor },
      { label: 'Vencimento', value: r.meta.venc },
      { label: 'CNPJ', value: maskCNPJ(r.meta.cnpj), lock: true },
      { label: 'E-mail', value: maskEmail(r.meta.email), lock: true },
      { label: 'Status', value: r.stage },
      { label: 'Dono', value: 'Financeiro (você)' },
    ],
    tableCols: [
      { header: 'Cliente', get: (r) => r.name, primary: true },
      { header: 'Valor', get: (r) => r.meta.valor },
      { header: 'Vencimento', get: (r) => r.meta.venc },
      { header: 'Status', stage: true },
    ],
    newForm: {
      title: 'Nova fatura',
      add: '+ Nova fatura',
      fields: [
        { label: 'Cliente', def: 'Contoso' },
        { label: 'Valor', def: 'R$ 4.200' },
        { label: 'Vencimento', def: 'vence em 15 dias' },
      ],
      build: (v) => ({
        name: v[0] || 'Contoso',
        meta: {
          valor: v[1] || 'R$ 4.200',
          venc: v[2] || 'vence em 15 dias',
          email: 'financeiro@contoso.com',
          cnpj: '99.888.777/0001-66',
        },
      }),
    },
    magic:
      'As faturas da planilha já estão na tela, com o total em risco no topo. Mexe à vontade: clique num stat pra filtrar, abra uma fatura.',
    touchHint: 'abre uma fatura ou clica num indicador pra filtrar',
    hitl: {
      text: 'A fatura da **AgroData (R$ 8.900)** está 12 dias vencida. Preparei a cobrança com proposta de parcelamento em 2x — envio?',
      button: 'Aprovar envio',
      note: 'Você aprovou: cobrança para AgroData',
      lead: 'Cobrança enviada.',
      resolveLabel: 'Você aprovou o envio',
      apply: { id: 'agro', toStage: 'Em negociação', log: 'Cobrança enviada com proposta de parcelamento — aprovada por você' },
    },
    evolve: {
      userMsg: 'Adiciona a etapa Acordo antes de Paga.',
      col: 'Acordo',
      before: 'Paga',
      move: { id: 'finops', from: 'Em negociação', to: 'Acordo', log: 'Movida para Acordo — parcelamento combinado com o cliente' },
      allyViaChat:
        'É assim que se evolui — pedindo. Nesta demonstração eu aplico um exemplo pronto: o status Acordo antes de Paga. Olha o painel:',
      doneLabel: 'status Acordo na régua',
    },
  },

  // ---------------------------------------------------------------- ATENDIMENTO (chats)
  atendimento: {
    id: 'atendimento',
    surface: 'chats',
    pill: '📅 Atendimento no WhatsApp que resolve — agenda lotada de mensagens',
    tema: 'atendimento no WhatsApp',
    xlsx: 'pacientes.xlsx (2 abas · 20 linhas)',
    planilhaRead:
      'Li sua planilha. A aba "Pacientes" tem 15 pacientes (colunas viram campos) · "Convênios" tem 5 — detectei CPF e já vou proteger. Entendi: atender no WhatsApp, agendar e remarcar consultas e confirmar presença — hoje uma pessoa responde tudo, o dia inteiro. Seus dados entram de verdade, sem redigitar nada.',
    espelhoChips: ['Pacientes', 'Agenda', 'Conversas'],
    premissas: [
      {
        icon: '🕒',
        kind: 'edit',
        before: 'Atendimento **seg–sex, 8h–18h**',
        after: 'Atendimento **seg–sex 8h–18h + sábado até 12h**',
        userMsg: 'Sábado de manhã também temos agenda.',
        ally: 'Sábado até 12h ✓ — anotado.',
      },
      { icon: '🤖', text: 'O assistente **agenda, remarca e confirma sozinho**' },
      { icon: '🚨', text: 'Assunto clínico ou urgência → **uma pessoa assume na hora**' },
      { icon: '🔒', text: 'Dado de saúde **nunca circula no chat**' },
    ],
    ajusteLabel: 'Aceito, com seu ajuste no horário',
    desenho: [
      { icon: '🗃️', label: 'Seus dados', text: 'Pacientes, agenda e conversas ligados, com os 20 registros da planilha' },
      { icon: '🖥️', label: 'Sua tela', text: 'Fila de conversas por status, com a agenda do dia ao lado' },
      { icon: '🤖', label: 'Seu assistente', text: 'Atende e executa: agenda, remarca, confirma — não é um chat que só responde' },
      { icon: '🔁', label: 'Automação', text: 'Consulta marcada → confirmação automática na véspera' },
      { icon: '🔌', label: 'Conexão', text: 'WhatsApp e agenda (Google Calendar)' },
      { icon: '🛡️', label: 'Quem vê o quê', text: 'Assunto clínico só para a equipe · CPF protegido' },
    ],
    buildSteps: [
      'Guardando seus dados — 15 pacientes, agenda, conversas',
      'Protegendo CPF e dados de saúde no mesmo ato — nada nasce desprotegido',
      'Montando sua fila de conversas',
      'Ligando o assistente e as confirmações automáticas',
      'Conferindo tudo por dentro — cada peça bate com o desenho',
    ],
    columns: ['Novo', 'Em atendimento', 'Aguardando paciente', 'Resolvido'],
    extraN: 8,
    seed: [
      {
        id: 'marina',
        name: 'Marina Lopes',
        stage: 'Novo',
        meta: { pedido: 'quer remarcar para quinta', cpf: '123.456.789-01' },
        thread: [
          { who: 'user', text: 'Oi, preciso remarcar minha consulta 🙏', time: '09:12' },
          { who: 'user', text: 'Consigo passar para quinta?', time: '09:12' },
        ],
        nba: { text: 'Remarcar para quinta às 14h e confirmar no calendário.', kind: 'advance', log: 'Pronto! Remarquei para quinta, 14h ✓ Já atualizei sua agenda.' },
      },
      {
        id: 'jose',
        name: 'José Neto',
        stage: 'Novo',
        meta: { pedido: 'primeira consulta, pediu horário', cpf: '234.567.890-12' },
        thread: [
          { who: 'user', text: 'Oi, queria marcar primeira consulta', time: '10:03' },
          { who: 'agent', text: 'Claro! Tenho amanhã às 10h ou quinta às 14h. Qual fica melhor?', time: '10:03' },
          { who: 'user', text: 'Amanhã 10h', time: '10:05' },
        ],
      },
      {
        id: 'paula',
        name: 'Paula Reis',
        stage: 'Em atendimento',
        meta: { pedido: 'perguntou sobre resultado de exame', cpf: '345.678.901-23' },
        thread: [{ who: 'user', text: 'Oi, saiu o resultado do meu exame de sangue?', time: '11:20' }],
        nba: {
          text: 'Assunto clínico — o assistente não responde: encaminhar para a equipe agora.',
          kind: 'handoff',
          log: '🙋 Assunto clínico — o assistente não responde: encaminhado para a equipe.',
        },
      },
      {
        id: 'carlos',
        name: 'Carlos Dias',
        stage: 'Aguardando paciente',
        meta: { pedido: 'confirmar presença amanhã', cpf: '456.789.012-34' },
        thread: [
          { who: 'agent', text: 'Olá, Carlos! Passando para lembrar da sua consulta amanhã às 15h. Confirma presença?', time: '08:30' },
          { who: 'user', text: 'Confirmo, estarei lá 👍', time: '08:41' },
          { who: 'agent', text: 'Perfeito, presença confirmada ✓ Até amanhã!', time: '08:41' },
        ],
      },
      {
        id: 'rita',
        name: 'Rita Souza',
        stage: 'Novo',
        meta: { pedido: 'dúvida de convênio', cpf: '567.890.123-45' },
        thread: [{ who: 'user', text: 'Vocês atendem pelo convênio Unimed?', time: '14:02' }],
      },
    ],
    touchId: 'jose',
    autoMove: { id: 'rita', toStage: 'Em atendimento', log: 'Sim, atendemos Unimed! Quer que eu já agende? ✓' },
    nbaDefault: () => ({ text: 'Responder e agendar — o assistente resolve e confirma.', kind: 'advance', log: 'Respondido e encaminhado ✓' }),
    appTitle: 'Atendimento — WhatsApp',
    boardLabel: 'Fila',
    ctaObj: 'um atendimento',
    subtitle: (r) => r.meta.pedido,
    recordFields: (r) => [
      { label: 'Paciente', value: r.name },
      { label: 'Pedido', value: r.meta.pedido },
      { label: 'CPF', value: maskCPF(r.meta.cpf), lock: true },
      { label: 'Status', value: r.stage },
      { label: 'Dono', value: 'Atendente (você)' },
    ],
    tableCols: [
      { header: 'Paciente', get: (r) => r.name, primary: true },
      { header: 'Pedido', get: (r) => r.meta.pedido },
      { header: 'Status', stage: true },
    ],
    newForm: {
      title: 'Nova conversa',
      add: '+ Nova conversa',
      fields: [
        { label: 'Paciente', def: 'Lucas Alves' },
        { label: 'Pedido', def: 'quer marcar avaliação' },
        { label: 'CPF', def: '678.901.234-56' },
      ],
      build: (v) => ({
        name: v[0] || 'Lucas Alves',
        meta: { pedido: v[1] || 'quer marcar avaliação', cpf: v[2] || '678.901.234-56' },
      }),
    },
    magic:
      'As conversas da planilha já estão na fila. Mexe à vontade: abra uma conversa e veja o assistente atendendo — ele agenda, confirma e passa o clínico pra equipe.',
    touchHint: 'abre uma conversa da fila',
    hitl: {
      text: 'O **José pediu primeira consulta amanhã às 10h** — a agenda está livre. Confirmo o agendamento?',
      button: 'Confirmar agendamento',
      note: 'Você aprovou: consulta do José confirmada',
      lead: 'Consulta confirmada.',
      resolveLabel: 'Você confirmou o agendamento',
      apply: { id: 'jose', toStage: 'Aguardando paciente', log: 'Agendado! Amanhã às 10h ✓ Confirmação enviada.' },
    },
    evolve: {
      userMsg: 'Liga a confirmação automática na véspera.',
      regra: '🔔 confirma véspera ✓',
      allyViaChat:
        'É assim que se evolui — pedindo. Nesta demonstração eu ligo um exemplo pronto: confirmação automática na véspera. Olha as regras do atendimento:',
      doneLabel: 'confirmação automática na véspera',
    },
  },
};

export const DEMO_COPY_PT: DemoCopy = {
  brandHref: '/',
  stages: ['Espelho', 'Enquadrar', 'Desenho', 'Rascunho vivo', 'É isso?', 'Operar', 'Publicar', 'Evoluir'],
  statusColor: {
    Novo: 'blue',
    'Em atendimento': 'amber',
    'Aguardando paciente': 'violet',
    Resolvido: 'green',
    'A vencer': 'blue',
    Vencida: 'red',
    'Em negociação': 'amber',
    Acordo: 'violet',
    Paga: 'green',
  },
  currency: (n) => 'R$ ' + n.toLocaleString('pt-BR'),
  route: {
    caixa: /fatur|cobran|caixa|receb|boleto|inadimpl/,
    atendimento: /atend|agend|consult|whatsapp|paciente|marcar/,
  },
  entry: {
    greeting:
      'Oi! Eu sou a Ally 👋 Escolha um exemplo aqui embaixo — ou me conta um problema do seu negócio com as suas palavras, que eu leio como você trabalha hoje. Os dois caminhos valem.',
    examples: [
      'meus leads e contratos vivem numa planilha…',
      'cobrança de clientes em atraso, tudo no caixa…',
      'minha clínica se afoga em mensagens no WhatsApp…',
    ],
  },
  cenarios: CENARIOS,
  trustRules: TRUST_RULES,
  ctaBeta: CTA.beta,

  flow: {
    prosaAlly: (tema) =>
      `Boa! É exatamente assim que funciona: você escreve, eu entendo e monto. Nesta demonstração eu sigo um exemplo pronto — ${tema} — mas o caminho é o mesmo com o SEU problema. Olha:`,
    resolvedEspelho: 'Confirmado por você',
    allyConfirmaFunciona: 'Então deixa eu confirmar como seu negócio funciona — corrija só o que estiver errado:',
    enquadrarAceito: 'Aceito como proposto',
    allyDesenhei: 'Desenhei seu app inteiro. Em português, não em jargão:',
    resolvedDesenho: 'Você mandou montar',
    origemPlanilha: 'da sua planilha',
    importadoPlanilha: (arquivo) => `Importado da planilha ${arquivo}`,
    allyAppDePe: (magic) => `🎉 Seu app está de pé — em rascunho, só seu. ${magic} Depois me diz se é isso.`,
    allyExperimenta: (touchHint) =>
      `Experimenta mexer no app primeiro — ${touchHint}. Decidir vendo é o combinado. 😉`,
    resolvedGate: 'Você ficou com ele — decidiu vendo',
    noteAppAprovado: (time) => `App aprovado por você, vendo-o funcionar · ${time}`,
    allyAssumeDia: 'Agora a Ally assume o dia a dia — e te pergunta antes do que importa. Olha ela trabalhando:',
    ajustarUserMsg: (alvo, entryCol) => `Queria ${alvo} logo depois de ${entryCol}.`,
    allyTroquei: 'Troquei — olha a tela. Ajustar rascunho é conversa, não retrabalho. É isso?',
    allyDescartar:
      'Se descartar, eu removo TUDO do rascunho — não sobra nada no seu espaço. (Nesta demonstração, sigo aqui se mudar de ideia.)',
    allyAutomacaoSegue: (lead) =>
      `${lead} A automação segue até o fim e fica registrada. Antes de abrir pro seu time, eu provo por dentro que cada papel vê só o combinado — aí você publica:`,
    resolvedPublicar: 'Publicado para o time',
    allyAppVivo: '🏁 App vivo, governado e trabalhando. Daqui pra frente, evoluir é só conversar — experimenta:',
    allyAplicado: 'Aplicado ✓ — mudança simples não pede cerimônia. E tem Desfazer, porque errar não pode machucar.',
    allyAnotei:
      'Anotei! No produto é assim mesmo: você escreve, eu faço. Nesta demonstração eu sigo um roteiro — a próxima decisão está no card aqui em cima (ou use as setas ▶ lá no topo).',
    resolvedHitlLater: 'Deixado para depois — fica na sua fila',
    logVoceMoveu: (next) => `Você moveu para ${next}`,
    logCriadoDireto: 'Criado por você, direto na tela do rascunho',
    origemCriado: 'criado por você',
    logEncaminhado: 'Encaminhado para um humano',
    logFeito: 'Feito ✓',
    logProximoPasso: 'Próximo passo executado pelo assistente — com o seu OK',
  },

  cards: {
    espelhoKick: 'Espelho — é isso?',
    espelhoChipNew: 'app novo — nada do que você já tem cobre isso',
    espelhoBtn: 'É isso ✓',
    enquadrarKick: 'Confirme como funciona — corrija por exceção',
    ajustadoPorVoce: '(ajustado por você)',
    corrigir: 'corrigir',
    enquadrarBtn: 'Está certo →',
    desenhoKick: 'O desenho do seu app',
    desenhoVerified: '✓ verificação interna: desenho completo e coerente, ponta a ponta',
    desenhoBtn: 'Monta o rascunho pra eu ver →',
    gateKick: 'Sua decisão — olhando pra coisa',
    gateP:
      'Você decide **vendo e usando**, não aprovando uma lista técnica. Ajustar é barato; descartar remove tudo, sem sobras.',
    gateKeep: 'Ficar com ele ✓',
    gateAdjust: 'Ajustar',
    gateDiscard: 'Descartar',
    hitlKick: 'Decisão sua — a Ally espera',
    hitlLater: 'Agora não',
    publicarKick: 'Abrir pro time?',
    publicarP:
      'Provado por dentro antes de expor: cada papel vê exatamente o combinado, dados sensíveis protegidos, automação conferida — **no banco, não no papel**.',
    publicarBtn: 'Publicar para o time',
    evoluirKick: 'Evoluir é conversar',
    evoluirApplied: 'Aplicado ✓',
    desfazer: 'Desfazer',
    evoluirReverted: '↩︎ Revertido por você — sem perder nenhum dado. **Errar não machuca.**',
    ctaKick: 'Isso, com os SEUS dados',
    ctaP: (ctaObj) =>
      `Você acabou de criar, aprovar vendo e operar ${ctaObj} — com dados de exemplo. Com a sua planilha de verdade, é o mesmo caminho.`,
    buildKick: 'Montando seu rascunho — zero perguntas',
  },

  app: {
    assistenteMoveu: 'assistente moveu',
    mover: 'mover →',
    moverAria: (name) => `Mover ${name}`,
    maisDaPlanilha: (n) => `+${n} da planilha`,
    finEmAberto: 'Em aberto',
    finVencido: 'Vencido',
    finEmNegociacao: 'Em negociação',
    limparFiltro: 'limpar filtro',
    finContador: (n) => `${n} faturas · toque num indicador para filtrar`,
    finTableHead: ['Cliente', 'Valor', 'Vencimento', 'Status'],
    abrir: 'abrir →',
    nenhumaFatura: 'Nenhuma fatura neste filtro.',
    regrasAtendimentoAria: 'Regras do atendimento',
    regraAgenda: '🤖 agenda sozinho ✓',
    regraClinico: '🙋 clínico → humano ✓',
    novo: 'NOVO',
    naoLidaAria: 'não lida',
    maisConversas: (n) => `+${n} conversas da planilha`,
    humanoAssume: '🙋 Humano assume',
    sugestaoAssistente: '🤖 Sugestão do assistente',
    proximoPassoSugerido: '🤖 Próximo passo sugerido',
    fazerIsso: 'Fazer isso',
    protegidoTitle: 'Protegido: seu papel vê mascarado — decidido no desenho',
    historico: 'Histórico — tudo fica registrado',
    badgeDraft: 'rascunho — só você vê',
    badgeKept: 'aprovado por você',
    badgePub: 'publicado para o time',
    appAria: 'Seu app',
    emptyTitle: 'Seu app vai aparecer aqui',
    emptySub: 'primeiro em rascunho — você aprova o que vê.',
    viewModeAria: 'Modo de visualização',
    tabela: 'Tabela',
    buscarPlaceholder: 'Buscar…',
    buscarAria: 'Buscar registro',
    tabelaContador: (shown, total) => `${shown} exibidos · ${total} no total`,
    trustAria: 'Regras da confiança demonstradas',
  },

  shell: {
    brandAria: 'Voltar ao site Fluxomind',
    crumbCompany: 'sua-empresa',
    crumbTitle: 'Jornada de criação',
    navAria: 'Navegar pela jornada passo a passo',
    voltarPasso: 'Voltar um passo',
    passoAPasso: 'passo a passo',
    avancarPasso: 'Avançar um passo',
    recomecarTitle: 'Reiniciar a demonstração e escolher outro exemplo',
    recomecar: ' Recomeçar',
    phaseFull: 'demonstração · produto em construção',
    phaseShort: 'em construção',
    ctaShort: 'Quero isso',
    railAria: 'Etapas da jornada',
    conversaAria: 'Conversa',
    you: 'VC',
    inputStarted: 'Escreva aqui — ex.: adiciona uma etapa no funil…',
    inputIdle: 'Ou escreva com as suas palavras o problema do seu negócio…',
    inputAria: 'Mensagem para a Ally',
    enviarAria: 'Enviar mensagem',
    panebarAria: 'Alternar entre conversa e app',
    paneChat: '💬 Conversa',
    paneApp: '▦ Seu app',
    decisaoPendenteAria: 'decisão pendente',
    novidadeAria: 'novidade no app',
    honest:
      'Demonstração interativa com dados de exemplo — ilustra a jornada de criação; o app real nasce dentro da plataforma, com os seus dados.',
    modalProtegido: '🛡️ Vira registro real no seu espaço — protegido e só seu.',
    criar: 'Criar',
    cancelar: 'Cancelar',
  },
};
